<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="16.1.1" />
		<PackageReference Include="Azure.Identity" Version="1.21.0" />
		<PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="6.0.0" />
		<PackageReference Include="Polly" Version="8.7.0" />
		<PackageReference Include="SFA.DAS.Http" Version="3.2.69" />
	</ItemGroup>
  <ItemGroup>
    <!-- transitive packages due to SFA.DAS.Http-->
    <!-- deprecated warning for Microsoft.IdentityModel.Clients.ActiveDirectory should be resolved when SFA.DAS.Http is upgraded-->
    <!-- deprecated warning for NLog.Config should be resolved when SFA.DAS.Http is upgraded-->
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="10.0.9" />
  </ItemGroup>
  
	<ItemGroup>
		<ProjectReference Include="..\SFA.DAS.Assessor.Domain\SFA.DAS.Assessor.Functions.Domain.csproj" />
		<ProjectReference Include="..\SFA.DAS.Assessor.Functions.Infrastructure\SFA.DAS.Assessor.Functions.Infrastructure.csproj" />
	</ItemGroup>

</Project>
